/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_CADENA 255
#define MAX_VECTOR 32

struct paquete_rpc {
	int x;
	int y;
	int z;
};
typedef struct paquete_rpc paquete_rpc;

typedef char *t_clave;

typedef char *t_valor1;

typedef struct {
	u_int t_vector_value2_len;
	float *t_vector_value2_val;
} t_vector_value2;

struct rpc_get_value_res {
	int status;
	t_valor1 value1;
	int N_value2;
	t_vector_value2 V_value2;
	paquete_rpc value3;
};
typedef struct rpc_get_value_res rpc_get_value_res;

struct rpc_set_value_1_argument {
	t_clave key;
	t_valor1 value1;
	int N_value2;
	t_vector_value2 V_value2;
	paquete_rpc value3;
};
typedef struct rpc_set_value_1_argument rpc_set_value_1_argument;

struct rpc_modify_value_1_argument {
	t_clave key;
	t_valor1 value1;
	int N_value2;
	t_vector_value2 V_value2;
	paquete_rpc value3;
};
typedef struct rpc_modify_value_1_argument rpc_modify_value_1_argument;

#define CLAVESRPC_PROG 0x31230001
#define CLAVESRPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPC_DESTROY 1
extern  enum clnt_stat rpc_destroy_1(int *, CLIENT *);
extern  bool_t rpc_destroy_1_svc(int *, struct svc_req *);
#define RPC_SET_VALUE 2
extern  enum clnt_stat rpc_set_value_1(t_clave , t_valor1 , int , t_vector_value2 , paquete_rpc , int *, CLIENT *);
extern  bool_t rpc_set_value_1_svc(t_clave , t_valor1 , int , t_vector_value2 , paquete_rpc , int *, struct svc_req *);
#define RPC_GET_VALUE 3
extern  enum clnt_stat rpc_get_value_1(t_clave , rpc_get_value_res *, CLIENT *);
extern  bool_t rpc_get_value_1_svc(t_clave , rpc_get_value_res *, struct svc_req *);
#define RPC_MODIFY_VALUE 4
extern  enum clnt_stat rpc_modify_value_1(t_clave , t_valor1 , int , t_vector_value2 , paquete_rpc , int *, CLIENT *);
extern  bool_t rpc_modify_value_1_svc(t_clave , t_valor1 , int , t_vector_value2 , paquete_rpc , int *, struct svc_req *);
#define RPC_DELETE_KEY 5
extern  enum clnt_stat rpc_delete_key_1(t_clave , int *, CLIENT *);
extern  bool_t rpc_delete_key_1_svc(t_clave , int *, struct svc_req *);
#define RPC_EXIST 6
extern  enum clnt_stat rpc_exist_1(t_clave , int *, CLIENT *);
extern  bool_t rpc_exist_1_svc(t_clave , int *, struct svc_req *);
extern int clavesrpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPC_DESTROY 1
extern  enum clnt_stat rpc_destroy_1();
extern  bool_t rpc_destroy_1_svc();
#define RPC_SET_VALUE 2
extern  enum clnt_stat rpc_set_value_1();
extern  bool_t rpc_set_value_1_svc();
#define RPC_GET_VALUE 3
extern  enum clnt_stat rpc_get_value_1();
extern  bool_t rpc_get_value_1_svc();
#define RPC_MODIFY_VALUE 4
extern  enum clnt_stat rpc_modify_value_1();
extern  bool_t rpc_modify_value_1_svc();
#define RPC_DELETE_KEY 5
extern  enum clnt_stat rpc_delete_key_1();
extern  bool_t rpc_delete_key_1_svc();
#define RPC_EXIST 6
extern  enum clnt_stat rpc_exist_1();
extern  bool_t rpc_exist_1_svc();
extern int clavesrpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paquete_rpc (XDR *, paquete_rpc*);
extern  bool_t xdr_t_clave (XDR *, t_clave*);
extern  bool_t xdr_t_valor1 (XDR *, t_valor1*);
extern  bool_t xdr_t_vector_value2 (XDR *, t_vector_value2*);
extern  bool_t xdr_rpc_get_value_res (XDR *, rpc_get_value_res*);
extern  bool_t xdr_rpc_set_value_1_argument (XDR *, rpc_set_value_1_argument*);
extern  bool_t xdr_rpc_modify_value_1_argument (XDR *, rpc_modify_value_1_argument*);

#else /* K&R C */
extern bool_t xdr_paquete_rpc ();
extern bool_t xdr_t_clave ();
extern bool_t xdr_t_valor1 ();
extern bool_t xdr_t_vector_value2 ();
extern bool_t xdr_rpc_get_value_res ();
extern bool_t xdr_rpc_set_value_1_argument ();
extern bool_t xdr_rpc_modify_value_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVESRPC_H_RPCGEN */
