/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_paquete_rpc (XDR *xdrs, paquete_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_clave (XDR *xdrs, t_clave *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_CADENA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_valor1 (XDR *xdrs, t_valor1 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_CADENA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_vector_value2 (XDR *xdrs, t_vector_value2 *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->t_vector_value2_val, (u_int *) &objp->t_vector_value2_len, MAX_VECTOR,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_get_value_res (XDR *xdrs, rpc_get_value_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_t_valor1 (xdrs, &objp->value1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_t_vector_value2 (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_set_value_1_argument (XDR *xdrs, rpc_set_value_1_argument *objp)
{
	 if (!xdr_t_clave (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_t_valor1 (xdrs, &objp->value1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_t_vector_value2 (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_modify_value_1_argument (XDR *xdrs, rpc_modify_value_1_argument *objp)
{
	 if (!xdr_t_clave (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_t_valor1 (xdrs, &objp->value1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_t_vector_value2 (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
