/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "clavesRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpc_destroy_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, RPC_DESTROY, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_set_value_1(t_clave key, t_valor1 value1, int N_value2, t_vector_value2 V_value2, paquete_rpc value3, int *clnt_res,  CLIENT *clnt)
{
	rpc_set_value_1_argument arg;
	arg.key = key;
	arg.value1 = value1;
	arg.N_value2 = N_value2;
	arg.V_value2 = V_value2;
	arg.value3 = value3;
	return (clnt_call (clnt, RPC_SET_VALUE, (xdrproc_t) xdr_rpc_set_value_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_get_value_1(t_clave key, rpc_get_value_res *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RPC_GET_VALUE,
		(xdrproc_t) xdr_t_clave, (caddr_t) &key,
		(xdrproc_t) xdr_rpc_get_value_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_modify_value_1(t_clave key, t_valor1 value1, int N_value2, t_vector_value2 V_value2, paquete_rpc value3, int *clnt_res,  CLIENT *clnt)
{
	rpc_modify_value_1_argument arg;
	arg.key = key;
	arg.value1 = value1;
	arg.N_value2 = N_value2;
	arg.V_value2 = V_value2;
	arg.value3 = value3;
	return (clnt_call (clnt, RPC_MODIFY_VALUE, (xdrproc_t) xdr_rpc_modify_value_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_delete_key_1(t_clave key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RPC_DELETE_KEY,
		(xdrproc_t) xdr_t_clave, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_exist_1(t_clave key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, RPC_EXIST,
		(xdrproc_t) xdr_t_clave, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
